"""Backend selection, SQL binding, and fail-closed behaviour without any network."""
from contextlib import closing
import os
from pathlib import Path
import sqlite3
import tempfile
import unittest
from unittest.mock import Mock, patch

import database as db
import database_backup


class DatabaseAdapterTests(unittest.TestCase):
    def settings(self, **values):
        with patch.dict(os.environ, values, clear=True):
            return db.DatabaseSettings.from_environment(Path(__file__).resolve().parents[1])

    def test_local_default_remains_sqlite(self):
        settings = self.settings()
        self.assertEqual(settings.backend, "sqlite")
        self.assertEqual(Path(settings.path).name, "database.db")

    def test_postgres_url_selects_postgres_and_is_not_in_repr(self):
        url = "postgresql://test-user:private-password@db.example.com/mflow?sslmode=require"
        settings = self.settings(DATABASE_URL=url)
        self.assertEqual(settings.backend, "postgres")
        self.assertNotIn("private-password", repr(settings))
        self.assertEqual(settings.url, url)

    def test_postgres_missing_or_bad_url_never_falls_back(self):
        for url in ("", "file.db", "https://example.com/db", "postgresql://u:p@db.example.com/db",
                    "postgresql://u:p@db.example.com/db?sslmode=disable", "postgresql://u:p@db.example.com:bad/db"):
            with self.subTest(url=url), self.assertRaises(db.DatabaseUnavailable):
                self.settings(M_FLOW_DATABASE_BACKEND="postgres", DATABASE_URL=url)

    def test_sqlite_is_explicitly_selected_for_isolated_tests(self):
        settings = self.settings(M_FLOW_DATABASE_BACKEND="sqlite", M_FLOW_DATABASE="isolated.db",
                                 DATABASE_URL="never-use-this-production-url")
        self.assertEqual(settings.backend, "sqlite")
        self.assertEqual(settings.path, "isolated.db")

    def test_invalid_backend_is_rejected(self):
        with self.assertRaises(db.DatabaseUnavailable):
            self.settings(M_FLOW_DATABASE_BACKEND="mysql")

    def test_local_postgres_can_disable_tls_for_ci(self):
        self.assertEqual(self.settings(DATABASE_URL="postgresql://test:test@127.0.0.1/mflow_test?sslmode=disable").backend, "postgres")

    def test_connection_failure_redacts_credentials_and_does_not_open_sqlite(self):
        settings = self.settings(DATABASE_URL="postgresql://u:private-password@db.example.com/mflow?sslmode=require")
        with patch.object(db.psycopg, "connect", side_effect=db.psycopg.OperationalError(settings.url)), patch.object(db.sqlite3, "connect") as sqlite_connect:
            with self.assertRaises(db.DatabaseUnavailable) as error:
                db.connect_database(settings)
            sqlite_connect.assert_not_called()
            self.assertNotIn("private-password", str(error.exception))

    def test_sqlite_preserves_foreign_keys_and_named_rows(self):
        with tempfile.TemporaryDirectory() as directory:
            with closing(db.connect_database(db.DatabaseSettings("sqlite", str(Path(directory) / "isolated.db")))) as conn:
                self.assertEqual(conn.execute("PRAGMA foreign_keys").fetchone()[0], 1)
                self.assertEqual(conn.execute("SELECT 1 AS number").fetchone()["number"], 1)

    def test_placeholder_conversion_never_interpolates_values(self):
        raw = Mock()
        conn = db.PostgresConnection(raw)
        private = "'; DROP TABLE users; -- 100%?"
        conn.execute("SELECT '?' AS literal, ? AS value, '50%' AS percent -- ? ignored\n", (private,))
        raw.execute.assert_called_once_with("SELECT '?' AS literal, %s AS value, '50%%' AS percent -- ? ignored\n", (private,))

    def test_script_split_preserves_literals_and_comments(self):
        sql = "SELECT ';?'; SELECT 2 /* ; */; SELECT 3 -- ;\n;"
        self.assertEqual(len(list(db.statements(sql))), 3)

    def test_pg_schema_identity_is_native_and_parameters_remain_bound(self):
        raw = Mock()
        conn = db.PostgresConnection(raw)
        db.execute_schema(conn, "CREATE TABLE example(id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER)")
        sql = raw.execute.call_args.args[0]
        self.assertIn("GENERATED BY DEFAULT AS IDENTITY", sql)
        self.assertIn("user_id BIGINT", sql)
        self.assertNotIn("AUTOINCREMENT", sql)

    def test_record_works_like_sqlite_row(self):
        row = db.Record(("id", "name"), (3, "Имя"))
        self.assertEqual(row[0], 3)
        self.assertEqual(row["name"], "Имя")
        self.assertEqual(dict(row), {"id": 3, "name": "Имя"})
        self.assertEqual(tuple(row), (3, "Имя"))

    def test_project_write_locks_project_before_revision_read(self):
        raw = Mock()
        db.begin_project_write(db.PostgresConnection(raw), 42)
        raw.execute.assert_called_once_with("SELECT id FROM projects WHERE id=%s FOR UPDATE", (42,))

    def test_form_ids_reject_invalid_and_out_of_range_values(self):
        for value in (None, "", "oops", True, "0", "-1", str(2**70), "1.1"):
            with self.subTest(value=value), self.assertRaises(ValueError):
                db.form_database_id(value)
        self.assertEqual(db.form_database_id("42"), 42)

    def test_initialization_requires_direct_connection(self):
        settings = self.settings(DATABASE_URL="postgresql://u:p@ep-db-pooler.example.com/mflow?sslmode=require")
        with patch.dict(os.environ, {}, clear=True), self.assertRaises(db.DatabaseUnavailable):
            db.initialization_settings(settings)
        direct = "postgresql://u:p@ep-db.example.com/mflow?sslmode=require"
        with patch.dict(os.environ, DATABASE_URL_UNPOOLED=direct):
            self.assertEqual(db.initialization_settings(settings).url, direct)

    def test_postgres_backup_cannot_silently_copy_old_sqlite(self):
        with patch.dict(os.environ, M_FLOW_DATABASE_BACKEND="postgres"), self.assertRaises(database_backup.BackupError):
            database_backup.create_backup("unused.sqlite3")


if __name__ == "__main__":
    unittest.main()
